[package]
name = "shader-editor"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.23.0"
egui = "0.23.0"
egui_glow = "0.23.0"
env_logger = "0.11.8"
glow = "0.12.0"
log = "0.4.17"
notify = "6.1.1"
